version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Dockerlocal
    ports:
      - "10000:80"
    volumes:
      - .:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped